### ISSUE TITLE
ChemNER Model Prediction are not working

### ISSUE THREAD

**Issue by Pradnya-muluk** [Ozymandias314/ChemIENER#2]
When I am trying to run the model and passing the strings, the model unable to predict chemical entities correspond to their classes. It returns  empty list
I am running this inference on CPU based machine.
**Below are the output logs :**
~/Downloads/ChemIENER-main$ /usr/bin/python3 /home/azureuser/Downloads/ChemIENER-main/test1.py
best.ckpt: 100%|█████████████████████████████████████████████████████████████| 4.36G/4.36G [01:07<00:00, 64.9MB/s]
/home/azureuser/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Some weights of BertForTokenClassification were not initialized from the model checkpoint at dmis-lab/biobert-large-cased-v1.1 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]

**This is my inferance code :**

import torch
from chemiener.interface import ChemNER
from huggingface_hub import hf_hub_download

ckpt_path = hf_hub_download("Ozymandias314/ChemNERCkpt", "best.ckpt")

model = ChemNER(ckpt_path, device=torch.device('cpu'))

text = "The chemical formula for water is H2O"

predictions = model.predict_strings(text)
#predict_strings
print(predictions)

I tried with multiple different strings but same issue..please let me know the how could able to get the predictions correctly....

**Comment by Ozymandias314** [comment]
Hello, 

Apologies for the oversight and thanks for catching this. The code you wrote should work if you replace text with an array of strings, e.g. text = ["The chemical formula for water is H2O"]. This is because predict_strings was written to expect a list of strings. 

These changes have been reflected in the README as well.
